# Generated by Django 3.0.1 on 2019-12-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('tax', models.FloatField(blank=True, default=0)),
                ('month', models.CharField(blank=True, default='12', max_length=500, null=True)),
                ('year', models.CharField(blank=True, default='2019', max_length=500, null=True)),
                ('credittobank', models.FloatField(blank=True, default=0)),
                ('salaryAmount', models.FloatField(blank=True, default=0)),
                ('grossIncome', models.FloatField(blank=True, default=0)),
                ('nhis', models.FloatField(blank=True, default=0)),
                ('allowanceforHeads', models.FloatField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PensionCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pensionID', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pensionID', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='', max_length=500, null=True)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varadj', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SUtility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.075)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='STransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.1)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('pension_code', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('salaryAmount', models.FloatField(blank=True, default=0)),
                ('grossIncome', models.FloatField(blank=True, default=0)),
                ('nhis', models.FloatField(blank=True, default=0)),
                ('allowanceforHeads', models.FloatField(blank=True, default=0)),
                ('isCurrentStaff', models.BooleanField(blank=True, default=True, null=True)),
                ('tax', models.FloatField(blank=True, default=0)),
                ('pension_collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_collector', to='salaryapp.PensionCollector')),
                ('schoolBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='salaryapp.SchoolBranch')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.1)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SHousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.15)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEntertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.05)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entertainment', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.1)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SDressing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.075)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dressing', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SDomestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.05)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.3)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Positives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('refund', models.FloatField(blank=True, default=0)),
                ('tahfeez', models.FloatField(blank=True, default=0)),
                ('total', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positives', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.FloatField(blank=True, default=0.075)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pension', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='salaryapp.Staff'),
        ),
        migrations.CreateModel(
            name='Negatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('neg_schoolshop', models.FloatField(blank=True, default=0)),
                ('neg_schoolfeesadvloan', models.FloatField(blank=True, default=0)),
                ('neg_deduction', models.FloatField(blank=True, default=0)),
                ('neg_feeding', models.FloatField(blank=True, default=0)),
                ('pos_refund', models.FloatField(blank=True, default=0)),
                ('pos_tahfeez', models.FloatField(blank=True, default=0)),
                ('neg_total', models.FloatField(blank=True, default=0)),
                ('pos_total', models.FloatField(blank=True, default=0)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negatives', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=11)),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bankAccount', to='salaryapp.Staff')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
    ]
