# Generated by Django 3.0.1 on 2019-12-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0003_remove_bankaccount_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('staff', 'month', 'year')},
        ),
    ]
