# Generated by Django 3.0.1 on 2019-12-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0005_staff_isaccountsstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pension_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pension_collector', to='salaryapp.PensionCollector'),
        ),
    ]
