# Generated by Django 3.0.1 on 2019-12-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0006_auto_20191222_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='schoolBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='salaryapp.SchoolBranch'),
        ),
    ]
