# Generated by Django 3.0.1 on 2019-12-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0007_auto_20191222_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bankAccount', to='salaryapp.Bank'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
