# Generated by Django 3.0.2 on 2020-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0008_auto_20191222_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(blank=True, default='1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='year',
            field=models.CharField(blank=True, default='2020', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='allowanceforHeads',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='grossIncome',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nhis',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salaryAmount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
