# Generated by Django 3.0.2 on 2020-01-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0011_auto_20200129_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('staff', 'month', 'year')},
        ),
    ]
