# Generated by Django 3.0.2 on 2020-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0012_auto_20200129_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(blank=True, default='2', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
