# Generated by Django 3.0.2 on 2020-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0014_auto_20200209_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
