# Generated by Django 3.0.2 on 2020-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0015_auto_20200209_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='allowanceforHeads',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='credittobank',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='grossIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='nhis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='salaryAmount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pension',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pension',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.075, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sbasic',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sbasic',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sdomestic',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sdomestic',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.05, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sdressing',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sdressing',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.075, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seducation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seducation',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sentertainment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sentertainment',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.05, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shousing',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shousing',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.15, max_digits=10),
        ),
        migrations.AlterField(
            model_name='smeal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='smeal',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stransport',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stransport',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sutility',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sutility',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.075, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variableadjustment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
