# Generated by Django 3.0.2 on 2020-02-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0022_auto_20200222_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='pension_code',
        ),
    ]
