# Generated by Django 3.0.2 on 2020-02-22 16:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaryapp', '0023_remove_staff_pension_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdressing',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.1000000000000000055511151231257827021181583404541015625'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_pensioner',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sutility',
            name='constant',
            field=models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.1000000000000000055511151231257827021181583404541015625'), max_digits=10),
        ),
        migrations.CreateModel(
            name='SMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('constant', models.DecimalField(blank=True, decimal_places=5, default=Decimal('0.05000000000000000277555756156289135105907917022705078125'), max_digits=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='salaryapp.PaySlip')),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
    ]
